### ISSUE TITLE
Fonts don't download

### ISSUE THREAD

**Issue by yasuhito** [matsuyoshi30/harbor#94]
I'm creating a website on GitHub Pages with Harbor theme, but the individual article pages fail to download the fonts (e.g., [this page](https://yasuhito.github.io/post/20210317113230-%E3%82%B9%E3%82%AB%E3%83%A9%E3%83%BC%E8%A1%8C%E5%88%97/))

<img width="404" alt="CleanShot 2021-03-18 at 17 02 30@2x" src="https://user-images.githubusercontent.com/8810/111592185-ca996380-880b-11eb-8e42-bdd3469b8a25.png">

By the way, the above error does not appear in the index page.

The settings I am using are as follows:

```
theme = "harbor"
baseURL = "https://yasuhito.github.io/"
title = "Notes"
paginate = 10
languageCode = "ja"
DefaultContentLanguage = "ja"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
publishDir = "docs"
```

Sorry in advance if I've made a fundamental mistake.

**Comment by matsuyoshi30** [comment]
Hi @yasuhito, thanks for the reporting and sorry for the delay.

This causes by the font-face src in `/static/css/main.css`. This theme's CSS bundles in a single JS file (`bundle.js`) which every page has, so the 404 error does not happen in the index page (like `https://example.com`) because the font-face src like `../fonts/noto-sans ...` is correct, but the article pages (like `https://example.com/some-article`) have the incorrect path specification.

I'll consider how to fix it.

**Comment by matsuyoshi30** [comment]
Hi @yasuhito. I've fixed this issue. If you still have the same issue, please let me know!

**Comment by yasuhito** [comment]
@matsuyoshi30 Thank you! I confirmed that the problem has been fixed. ✨
